export const INITIAL_LOAD_APPS_SUCCESS = '@@INITIAL/APPS/SUCCESS';
export const INITIAL_LOAD_APPS_ERROR = '@@INITIAL/APPS/ERROR';

export const INSTANCE_CREATE_SUCCESS = '@@INSTANCE/CREATE/SUCCESS';
export const INSTANCE_CREATE_ERROR = '@@INSTANCE/CREATE/ERROR';

export const INSTANCE_EDIT_SUCCESS = '@@INSTANCE/EDIT/SUCCESS';
export const INSTANCE_EDIT_ERROR = '@@INSTANCE/EDIT/ERROR';

export const INSTANCE_CHECKIN_SUCCESS = '@@INSTANCE/CHECKIN/SUCCESS';
export const INSTANCE_CHECKIN_ERROR = '@@INSTANCE/CHECKIN/ERROR';

export const INSTANCE_LOAD_SUCCESS = '@@INSTANCE/LOAD/SUCCESS';
export const INSTANCE_LOAD_ERROR = '@@INSTANCE/LOAD/ERROR';

export const INSTANCE_DATA_LOAD_SUCCESS = '@@INSTANCE_DATA/LOAD/SUCCESS';
export const INSTANCE_DATA_LOAD_ERROR = '@@INSTANCE_DATA/LOAD/ERROR';

export const LOAD_FORMS_SUCCESS = 'LOAD_FORMS_SUCCESS';
export const LOAD_FORMS_ERROR = 'LOAD_FORMS_ERROR';
export const CHECKIN_ERROR = 'CHECKIN_ERROR';
export const CHECKIN_RESET_ERROR = 'CHECKIN_RESET_ERROR';

export const LOAD_FORM_DATA_SUCCESS = 'LOAD_FORM_DATA_SUCCESS';
export const LOAD_FORM_DATA_ERROR = 'LOAD_FORM_DATA_ERROR';

export const LOAD_FORM_ENTRY_SUCCESS = 'LOAD_FORM_ENTRY_SUCCESS';
export const LOAD_FORM_ENTRY_ERROR = 'LOAD_FORM_ENTRY_ERROR';
export const CHECKIN_CLEAR_ENTRY = 'CHECKIN_CLEAR_ENTRY';

export const LOAD_BIND_FORM_SUCCESS = 'LOAD_BIND_FORM_SUCCESS';
export const LOAD_BIND_FORM_ERROR = 'LOAD_BIND_FORM_ERROR';

export const LOAD_RELEASE_SUCCESS= 'LOAD_RELEASE_SUCCESS';
export const LOAD_RELEASE_ERROR = 'LOAD_RELEASE_ERROR';

export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_ERROR = 'UPDATE_TOKEN_ERROR';

export const ASYNC_ERROR = 'ASYNC_ERROR';
